#!/bin/bash

alias apti='sudo apt-get install'
alias apts='apt-cache search'
alias aptss='apt-cache show'
alias aptu='sudo apt-get update'
alias aptuu='sudo apt-get upgrade'
alias aptf='apt-file search'
