#!/bin/bash

alias ls='ls --color=auto'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -l'
alias lla='ls -lA'

alias grep='grep --color=always'
alias grepn='grep -n'
alias less='less -R'

alias df='df -h'
alias du='du -h'

alias rm='rm -r --interactive=never'

function mkc() { mkdir -p $1; cd $1 || return; }

if [ -x /usr/bin/dircolors ]; then
  test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
fi
