#!/bin/bash

alias hostgit='git --git-dir=/host.git'

alias dotfiles='git --git-dir=$HOME/.dotfiles.git'
alias homekeeper='git --git-dir=$HOME/.home.git'
alias www='git --git-dir=$HOME/www/.lncr.git'

function gc {
#	echo "git clone https://github.com/$1"
	git clone https://github.com/$1
	cd $(echo $1|cut -d / -f 2)
}

function gc1 {
#	echo "git clone https://github.com/$1"
	git clone --depth 1 https://github.com/$1
	cd $(echo $1|cut -d / -f 2)
}

