#!/bin/bash

alias hostgit='git --git-dir=/host.git'

alias dotfiles='git --git-dir=$HOME/.dotfiles.git'
alias homekeeper='git --git-dir=$HOME/.home.git'
alias www='git --git-dir=$HOME/www/.lncr.git'
