#!/bin/bash

alias sshs='ssh server'
alias linode="ssh tgz.epac.to"


# simple webserver
webs() {
	while true; do
		{
			echo -e "HTTP/1.1 200 OK\r\n"
			cat $1
		} | nc -vl 8008
	done
}

# show filesize of some url
websize() {
	size=$(curl -sI $1 | grep -E "Location|Content-Length")
	if [[ $size == Location* ]]; then
		size=${size##* }
		size=$(curl -sI ${size::-1} | grep Content-Length)
	fi
	echo $size| awk '{print $2/1024/1024"MB"}'
}
