#!/bin/bash

alias epoch='date +%s'

# make alias parse the command after sudo and xargs
alias sudo='sudo '
alias xargs='xargs '

# use like `make; andTell` or `cp big.file ~/folder; notify-me`
alias andTell='notify-send --urgency=normal -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*andTell$//'\'')"'
